# Generated by Django 2.2 on 2021-08-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_tvshows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
